version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns: ["*"]
    labels: ["dependencies"]
    schedule:
      interval: monthly

  - package-ecosystem: maven
    directory: /
    groups:
      maven:
        patterns: ["*"]
    labels: ["dependencies"]
    schedule:
      interval: monthly

  - package-ecosystem: pre-commit
    directory: /
    groups:
      pre-commit:
        patterns: ["*"]
    labels: ["dependencies"]
    schedule:
      interval: monthly
