# exclude vendored files
exclude: '^(COPYING\.LESSER)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Check spelling with codespell
        additional_dependencies:
          - tomli  # Python < 3.11

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: local
    hooks:
      - id: mkmaintainer
        name: Sync maintainer issue templates
        entry: .github/maintainer/mkmaintainer.py
        files: .github/maintainer/
        language: python
        additional_dependencies: [PyYAML]
