# priorities:
# 0    - read-only
# 1000 - mutually non-conflicting fixers
# none - other fixers

# exclude vendored files
exclude: '^(COPYING\.LESSER)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-vcs-permalinks
        priority: 0
      - id: check-yaml
        priority: 0
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        name: Check spelling with codespell
        priority: 0
        additional_dependencies:
          - tomli  # Python < 3.11

  - repo: meta
    hooks:
      - id: check-hooks-apply
        priority: 0
      - id: check-useless-excludes
        priority: 0

  - repo: local
    hooks:
      - id: mkmaintainer
        name: Sync maintainer issue templates
        priority: 1000
        entry: .github/maintainer/mkmaintainer.py
        files: .github/maintainer/
        language: python
        additional_dependencies: [PyYAML]
